package httpapi

import (
	"bytes"
	"context"
	"errors"
	"io"
	"net/http"
	"sync"

	"github.com/google/uuid"

	"github.com/CDRO/Inventory/internal/store"
)

// IdempotencyKeyHeader names the header a client puts a retry-safe key in
// (docs/specs/12-client-api-contract.md).
const IdempotencyKeyHeader = "Idempotency-Key"

// IdempotentReplayHeader marks a response that was replayed from a stored
// record rather than produced by running the request again. Informational: a
// client needs nothing but the stored answer, but a person reading a log does.
const IdempotentReplayHeader = "Idempotent-Replayed"

// maxIdempotentBody bounds the body read for hashing. It is the upload cap plus
// room for multipart framing, since an upload is the largest write a client
// can queue offline and retry.
const maxIdempotentBody = MaxUploadBytes + 1<<20

// IdempotencyStore is the slice of the store the middleware uses.
type IdempotencyStore interface {
	LookupIdempotent(ctx context.Context, key string, userID uuid.UUID, requestHash string) (*store.IdempotentResponse, error)
	RecordIdempotent(ctx context.Context, key string, userID uuid.UUID, storageID *uuid.UUID, requestHash string, status int, body []byte) error
}

// Idempotency makes a write safe to repeat.
//
// A native client with an offline queue retries requests whose response never
// arrived — and some of those the server already applied. Without this, the
// retry of "consumed one jar" debits the jar twice. With it, a write carrying
// an Idempotency-Key runs once, and every repeat of the same key by the same
// user gets the stored answer back without executing anything
// (docs/specs/12-client-api-contract.md).
//
// Rules, each of which a test pins:
//
//   - No header, no change. The browser does not send one: its user can see
//     whether a click landed.
//   - The same key with a different method, path or body is 422, never a
//     replay. That is a client bug, and replaying would hand back the answer
//     to some other request while silently dropping this one.
//   - Only answers that are the request's real outcome are recorded: 2xx and
//     4xx. A 5xx or a 429 says "try again", so recording it would make the
//     retry the client was told to make return the same failure forever.
//   - Two copies of the same key racing each other run one at a time, so the
//     second becomes a replay of the first instead of a second execution.
//
// It must be mounted after RequireSession — keys are scoped per user — and,
// on storage routes, after RequireStorageMember, so a refused request is
// never recorded and a replay is re-authorized like any other request.
type Idempotency struct {
	store  IdempotencyStore
	errors *ErrorWriter
	locks  keyLocks
}

// NewIdempotency builds the middleware.
func NewIdempotency(s IdempotencyStore, errs *ErrorWriter) *Idempotency {
	return &Idempotency{store: s, errors: errs, locks: keyLocks{held: map[string]*keyLock{}}}
}

// Middleware wraps a router's write routes.
func (m *Idempotency) Middleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		key := r.Header.Get(IdempotencyKeyHeader)
		if key == "" || !isWrite(r.Method) {
			next.ServeHTTP(w, r)
			return
		}

		if _, err := uuid.Parse(key); err != nil {
			m.errors.WriteError(w, r, ValidationFailed(map[string][]string{
				IdempotencyKeyHeader: {"Must be a UUID generated by the client."},
			}, err))
			return
		}

		user, ok := UserFrom(r.Context())
		if !ok {
			// Mounted without RequireSession in front. A wiring mistake: refuse
			// rather than run the write unprotected.
			m.errors.WriteError(w, r, Internal(errors.New("httpapi: idempotency middleware mounted without a session")))
			return
		}

		body, err := io.ReadAll(http.MaxBytesReader(w, r.Body, maxIdempotentBody))
		if err != nil {
			var maxErr *http.MaxBytesError
			if errors.As(err, &maxErr) {
				m.errors.WriteError(w, r, PayloadTooLarge())
				return
			}
			m.errors.WriteError(w, r, ValidationFailed(map[string][]string{"body": {"The request body could not be read."}}, err))
			return
		}
		r.Body = io.NopCloser(bytes.NewReader(body))
		hash := store.HashRequest(r.Method, r.URL.RequestURI(), body)

		unlock := m.locks.lock(user.ID.String() + "\x00" + key)
		defer unlock()

		stored, err := m.store.LookupIdempotent(r.Context(), key, user.ID, hash)
		if errors.Is(err, store.ErrValidation) {
			m.errors.WriteError(w, r, &Failure{
				Status:  http.StatusUnprocessableEntity,
				Code:    CodeValidationFailed,
				Message: "The request could not be processed.",
				Fields: map[string][]string{
					IdempotencyKeyHeader: {"This key was already used for a different request."},
				},
				Err: err,
			})
			return
		}
		if err != nil {
			m.errors.WriteError(w, r, Internal(err))
			return
		}
		if stored != nil {
			replay(w, stored)
			return
		}

		rec := &recordingWriter{ResponseWriter: w, status: http.StatusOK}
		next.ServeHTTP(rec, r)

		if !worthRecording(rec.status) {
			return
		}
		recorded := rec.body.Bytes()
		if len(recorded) == 0 {
			recorded = nil
		}

		var storageID *uuid.UUID
		if id, ok := StorageIDFrom(r.Context()); ok {
			storageID = &id
		}

		// The response has already gone out, so a failure here cannot change
		// it; the cost is only that a retry would execute again. Logged, not
		// hidden. A request context cancelled by the client hanging up must
		// not stop the record being written — that client is precisely the
		// one about to retry.
		ctx := context.WithoutCancel(r.Context())
		if err := m.store.RecordIdempotent(ctx, key, user.ID, storageID, hash, rec.status, recorded); err != nil {
			m.errors.Log(r.Context(), "recording idempotent response failed", err)
		}
	})
}

func isWrite(method string) bool {
	switch method {
	case http.MethodPost, http.MethodPut, http.MethodPatch, http.MethodDelete:
		return true
	}
	return false
}

// worthRecording reports whether a status is the request's settled outcome.
func worthRecording(status int) bool {
	return status < 500 && status != http.StatusTooManyRequests
}

// replay writes a stored response. Every recorded body came from writeJSON or
// the error serializer, so it is JSON when there is one.
func replay(w http.ResponseWriter, stored *store.IdempotentResponse) {
	header := w.Header()
	header.Set(IdempotentReplayHeader, "true")
	header.Set("Cache-Control", "no-store")
	if len(stored.Body) > 0 {
		header.Set("Content-Type", "application/json; charset=utf-8")
	}
	w.WriteHeader(stored.Status)
	_, _ = w.Write(stored.Body)
}

// recordingWriter passes a response through while keeping a copy of it.
type recordingWriter struct {
	http.ResponseWriter
	status      int
	wroteHeader bool
	body        bytes.Buffer
}

func (rw *recordingWriter) WriteHeader(status int) {
	if !rw.wroteHeader {
		rw.status = status
		rw.wroteHeader = true
	}
	rw.ResponseWriter.WriteHeader(status)
}

func (rw *recordingWriter) Write(b []byte) (int, error) {
	rw.wroteHeader = true
	rw.body.Write(b)
	return rw.ResponseWriter.Write(b)
}

// keyLocks serializes requests that share a key.
//
// In-process is enough: this is a single-process server
// (docs/specs/01-architecture-and-deployment.md). Entries are reference
// counted and removed when the last holder leaves, so the map holds only keys
// that are in flight right now.
type keyLocks struct {
	mu   sync.Mutex
	held map[string]*keyLock
}

type keyLock struct {
	mu   sync.Mutex
	refs int
}

func (k *keyLocks) lock(key string) (unlock func()) {
	k.mu.Lock()
	l, ok := k.held[key]
	if !ok {
		l = &keyLock{}
		k.held[key] = l
	}
	l.refs++
	k.mu.Unlock()

	l.mu.Lock()
	return func() {
		l.mu.Unlock()
		k.mu.Lock()
		l.refs--
		if l.refs == 0 {
			delete(k.held, key)
		}
		k.mu.Unlock()
	}
}
